### ISSUE TITLE
asap_to_kite_error_10_21_21

### ISSUE THREAD

**Issue by sohanidassharma123** [caleblareau/asap_to_kite#2]
Hi there,

Thank you for sharing your new tool. I am trying to run it my Macbook. I have Python3.8. 
However I have some issues when running the code.

I appreciate if you provide me the answer:
1- which python version you are suggesting me to use?
2- I get an error on this command:
"opts.add_option("--nreads", '-n', default = 1000000, help="Maximum number of reads to process in one iteration. Decrease this if in a low memory environment (e.g. laptop). Default = 10,000,000.")"

And the error is:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/optparse.py", line 1008, in add_option
    self._check_conflict(option)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/optparse.py", line 980, in _check_conflict
    raise OptionConflictError(
optparse.OptionConflictError: option -n/--nreads: conflicting option string(s): -n, --nreads

Do you have any solution for me? Appreciate that.

Thanks,
Sohani

**Comment by caleblareau** [comment]
Any python version >3.y should be fine, so I don't think that's the issue. 

Can you indicate how you are running the script from the command line?

**Comment by sohanidassharma123** [comment]
Hi,
I am able to run asap_kite_v2.py but it is generating an error (see below)
when trying with the latest version. I am wondering if you could tell what
step is going off here?

***@***.*** asap_to_kite]$ python asap_to_kite_A_B.py -f ADT_A -s
ADT_A -o out_test

Traceback (most recent call last):

  File "/athena/namlab/scratch/sod4003/asap_to_kite/asap_to_kite_A_B.py",
line 43, in <module>

    A_barcodes = [line.rstrip('\n') for line in open(options.TSA)]

TypeError: expected str, bytes or os.PathLike object, not NoneType

***@***.*** asap_to_kite]$ python asap_to_kite_A_B.py -f test/data1 -s
test1 -o one_one

Traceback (most recent call last):

  File "/athena/namlab/scratch/sod4003/asap_to_kite/asap_to_kite_A_B.py",
line 43, in <module>

    A_barcodes = [line.rstrip('\n') for line in open(options.TSA)]

TypeError: expected str, bytes or os.PathLike object, not NoneType


Best regards,

Sohani

**Comment by caleblareau** [comment]
Hi, please see my response in the prior thread about the _A_B version. I will make a note in documentation about the use cases for these two different scripts.

**Comment by caleblareau** [comment]
Did the _v2 script not achieve what you wanted?

**Comment by sohanidassharma123** [comment]
Thanks,
Yes, these codes are running without errors. But, I am getting problem while using the kite workflow. I am not sure is it because of the fastqs which are not the correct format or there is something else. I am getting only 10% cells in the final counts file. Only thing, I can say is the fastq length of asapseq run and the PBMC test fastqs of kb_bustools are different. 

#code#
srun -n1 --pty --partition=panda --mem=128G bash -i 
module load python-3.7.6-gcc-8.2.0-hk56qj4
module load kallisto-0.46.2-gcc-8.2.0-hrkd3s2
module load kb-python/0.26.4
which kb
#Build the feature barcode mismatch index
python
import pandas as pd
import anndata
import numpy as np
import scanpy as sc

df = pd.read_csv('ASAPSeq003_barcodes.csv')
df
df[['sequence', 'id']].to_csv('features.tsv', index=None, header=None, sep='\t')
quit()
cat features.tsv
python3.7 /pbtech_mounts/software/apps/kb_python/0.26.4/bin/kb ref -i mismatch.idx -f1 mismatch.fa -g t2g.txt --workflow kite features.tsv 
python3.7 /pbtech_mounts/software/apps/kb_python/0.26.4/bin/kb count --h5ad -i mismatch.idx -g t2g.txt -w 737K-cratac-v1.txt -x 10xv3 --workflow kite -t2 ASAPSeq003_TSA_out_final_R1.fastq.gz ASAPSeq003_TSA_out_final_R2.fastq.gz --overwrite 
python
import pandas as pd
import anndata
import numpy as np
import scanpy as sc

adata = anndata.read_h5ad('counts_unfiltered/adata.h5ad')
sc.pp.filter_cells(adata, min_counts=0)
sc.pp.filter_genes(adata, min_counts=0)
fig=sc.pl.violin(adata, keys='n_counts')
adata.obs.index
fig=sc.pl.violin(adata, keys='n_counts',save='TSA_genes_counts_Nov21_2021_violin.pdf')

**Comment by caleblareau** [comment]
For asap, the `-x 10xv3` should be `-x 10xv2`

Otherwise, I haven't used `kb` so I can't really comment on it
